"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 06:16:30.021190
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Enum('ai', 'user', name='actor', native_enum=False, length=32), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn')
    )
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('cycle_length_days', sa.Integer(), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('tax_code', sa.String(length=20), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('backup_supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['backup_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=False),
    sa.Column('diagnosed_at', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('drug', 'consumable', name='itemtype', native_enum=False, length=32), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'sent', 'confirmed', 'received', name='postatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_by', sa.Enum('ai', 'human', name='pocreator', native_enum=False, length=32), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=50), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'paused', name='planstatus', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_next_due_date'), 'treatment_plans', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lot_no', sa.String(length=50), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_expiry_date'), 'batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_item_id'), 'batches', ['item_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_table('protocol_items',
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_cycle', sa.Integer(), nullable=False),
    sa.Column('dose_per_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('protocol_id', 'item_id')
    )
    op.create_table('supplier_price_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('min_order_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('qty_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('dispense', 'receive', 'waste', 'adjust', name='txnreason', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_txns_created_at'), 'stock_txns', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_txns_item_id'), 'stock_txns', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_txns_item_id'), table_name='stock_txns')
    op.drop_index(op.f('ix_stock_txns_created_at'), table_name='stock_txns')
    op.drop_table('stock_txns')
    op.drop_table('supplier_price_list')
    op.drop_table('protocol_items')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_batches_item_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_expiry_date'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_next_due_date'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_table('purchase_orders')
    op.drop_table('items')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_table('suppliers')
    op.drop_table('protocols')
    op.drop_table('patients')
    op.drop_table('forecast_runs')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
